### PR TITLE
do not force a specific version of DBIx::Class::Helpers

### PR DESCRIPTION
**Pull request by eseyman**
.

### CODE REVIEW

**Review by dylanwh — APPROVED** [review]

**Comment by justdave** [comment]
The test failure is a problem with the test, not with this patch.  @dylanwh know how to fix? It's a package dependency error deploying the test instance.

**Comment by CyberShadow** [comment]
> The test failure is a problem with the test, not with this patch. @dylanwh know how to fix? It's a package dependency error deploying the test instance.

https://github.com/bugzilla/harmony/pull/83 should fix that.

**Comment by CyberShadow** [comment]
What effect does this change have? What does this fix? What is the rationale? Is there a pre-existing discussion somewhere about this? If so, please link it.

**Comment by eseyman** [comment]
> What effect does this change have? What does this fix? What is the rationale? Is there a pre-existing discussion somewhere about this? If so, please link it.

I could have sworn this was written somewhere but I can't find it.

Anyway, in commit bc93e15d26f1c269bdd2c87696b676709e04d645, Dave committed a change that requires the exact version 2.034002 of DBIx::Class::Helpers for Bugzilla. Since it's highly unlikely that people will have that exact version on their system, I changed it to 2.034002 or higher.

**Comment by CyberShadow** [comment]
Thanks!

So, the use case is to run Bugzilla using dependencies installed via an external mechanism, such as a distribution's package manager?

**Comment by eseyman** [comment]
> Thanks!
> 
> So, the use case is to run Bugzilla using dependencies installed via an external mechanism, such as a distribution's package manager?

Yes. It's also useful when creating a package of bugzilla for your Linux distribution.

**Comment by CyberShadow** [comment]
I think this change should then be undone too:
https://github.com/bugzilla/harmony/commit/bc93e15d26f1c269bdd2c87696b676709e04d645#diff-7044641af21535cf56dd02365828d3b73a67a7282a5788f92707c6aef1924dafL25-R25

**Review by CyberShadow — APPROVED** [review]

**Pull request merged**
