### PR TITLE
Bug 1885709: Support for MySQL 8

### PR DESCRIPTION
**Pull request by justdave**
See [bug 1885709](https://bugzilla.mozilla.org/show_bug.cgi?id=1885709)

#### Details
Quote the table name when it involves the `groups` table, since it is now considered to be a reserved word in modern versions of MySQL.

#### Additional info
This commit was derived from the following one from BMO, in which  they use $dbh->quote_identifier(), which allows the different DBD::* drivers to use the appropriate quoting. https://github.com/mozilla-bteam/bmo/commit/5dc1b8c85c4e90c3467fd82cab9fca05fe2be74a

* [bmo#1592129](https://bugzilla.mozilla.org/show_bug.cgi?id=1592129)
* [bmo#1604051](https://bugzilla.mozilla.org/show_bug.cgi?id=1604051)
* companion to https://github.com/bugzilla/bugzilla/pull/153

### CODE REVIEW

**Comment by justdave** [comment]
That test_bmo failure is legit. Need to fix that before this lands.

**Comment by justdave** [comment]
This is still broken... I pushed my WIP though in case anyone else wants to mess with it.

Build instructions:
```bash
docker build -t bmo-cpanfile -f Dockerfile.cpanfile .
docker run -it -v "$(pwd):/app/result" bmo-cpanfile cp cpanfile cpanfile.snapshot /app/result
docker build -t bugzilla/bugzilla-perl-slim:20240314.1 -f Dockerfile.bmo-slim .
docker compose -f docker-compose.test.yml build
docker compose -f docker-compose.test.yml run bmo.test test_bmo -q -f t/bmo/*.t
```
That last line currently errors out with:
```
unable to connect to dbi:mysql:database=bugs;host=bmo.db as bugs: Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection. at /app/scripts/entrypoint.pl line 268.

It's definitely a build issue with the bugzilla-perl-slim image. If I used bmo-slim and compiled our missing libraries on top of it, then it worked, but that takes forever to build, so there's something else we're missing from BMO.

**Comment by justdave** [comment]
This depends on #109 and #110 (merged here, but those need to land first for the paperwork)

**Comment by justdave** [comment]
All of that trying to figure out why the test suddenly didn't pass, turned out to be because circleci wasn't rebuilding the test image between runs, which kinda defeats the purpose.  Ended up re-doing a decent chunk of the circleci config to make it all work.

As noted previously, This depends on #109 and #110 (merged here, but those need to land first for the paperwork) so go approve (and land) those first.

**Comment by justdave** [comment]
#111 also needs to land before this.

**Comment by justdave** [comment]
#112 also needs to land before this.

**Comment by justdave** [comment]
All the prereq PRs have landed and this is clear of non-related stuff now.  This is ready to land once I get an approval.

**Review by dylanwh — APPROVED** [review]

**Pull request merged**
