### PR TITLE
fix all the tests

### PR DESCRIPTION
**Pull request by dylanwh**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Any idea what's causing the

```
Can't locate object method "host" via package "URI::_generic" at /app/Bugzilla/Install/Filesystem.pm line 120.
```
?

Is `host` a recent thing?

**Comment by dylanwh** [comment]
I suspect the urlbase isn't beginning with http: there... weird

**Comment by CyberShadow** [comment]
The use of `urlbase` in `Filesystem.pm` was introduced in #28. If `urlbase` may not be available there then that case should probably be handled at that spot regardless. I'll have a look.

**Comment by dylanwh** [comment]
I got past that error for now. The problem is we have a 'magic' value for urlbase that is only applicable if the "entrypoint" is being executed. Probably the value of 'AUTOMATIC' should be in handled in Bugzilla/Install/Localconfig.pm but for now this seems to work a bit.

**Comment by dylanwh** [comment]
2 out of 4 ain't bad!

Now to figure out what else is going on.

**Pull request merged**
