### PR TITLE
extensions/BugModal: Enable bugzilla-readable-status unconditionally

### PR DESCRIPTION
**Pull request by CyberShadow**
I see no downside for enabling it always, and let it generate readable descriptions for the "Tracking" section. They appear useful even without the TrackingFlags extension.

This also removes some hard-coded BMO/Firefox-specific logic.

### CODE REVIEW

**Review by dylanwh — DISMISSED** [review]
Please remove the `if (1) { ... }` wrapping, that's not needed. I agree with this change other than this small nit.

**Comment by CyberShadow** [comment]
Done :)

**Review by dylanwh — APPROVED** [review]

**Comment by justdave** [comment]
Do we have a Bugzilla bug that goes with this PR?

**Comment by justdave** [comment]
Still don't see a bug filed to go with this.
If we hope to keep BMO following upstream in the future, shouldn't we move this code into the BMO extension and add a hook in this spot that it can hook to insert it back?

**Comment by CyberShadow** [comment]
Sorry, this is part of the BMO cleanup effort, so same bug as most other PRs from me.

**Comment by CyberShadow** [comment]
> If we hope to keep BMO following upstream in the future,

My understanding was that this was never an option, as the BMO team is uninterested in collaborating with any upstream.

**Comment by justdave** [comment]
> My understanding was that this was never an option, as the BMO team is uninterested in collaborating with any upstream.

Yeah, I guess that's pretty much the way it is.  They can cherry-pick if they want our stuff. And we'll do the same to theirs in the future.

**Comment by justdave** [comment]
> Sorry, this is part of the BMO cleanup effort, so same bug as most other PRs from me.

OK, so [bug 1446236](https://bugzilla.mozilla.org/show_bug.cgi?id=1446236)

**Comment by justdave** [comment]
FYI, this commit broke filing new bugs.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1892558

**Comment by justdave** [comment]
correction, it broke show_bug, not filing new ones.

**Comment by justdave** [comment]
This appears to have been missing from the patch: (I made this up based on the usage, but it seems to work)
```diff
diff --git a/Bugzilla.pm b/Bugzilla.pm
index e58d84f32..06aa3fb0a 100644
--- a/Bugzilla.pm
+++ b/Bugzilla.pm
@@ -135,6 +135,12 @@ sub extensions {
   return $extensions;
 }

+sub has_extension {
+  my (undef, $extension) = @_;
+  return 1 if (grep { $_ eq $extension } Bugzilla->extensions);
+  return 0;
+}
+
 sub cgi {
   return request_cache->{cgi} ||= Bugzilla::CGI->new;
 }
```

However, that leads to:

`Odd number of elements in anonymous hash at /app/extensions/BugModal/Extension.pm line 209.`

I don't think this was ready to land.

**Comment by justdave** [comment]
@CyberShadow We still need this, it just needs to be fixed before landing. It looks like your branch for it still exists.  Can you rebase it, re-file it as a new pull request referencing [bug 1446236](https://bugzilla.mozilla.org/show_bug.cgi?id=1446236), and fix the issues that caused it to get backed out?

Thanks!

**Comment by CyberShadow** [comment]
@justdave Apologies, we no longer use Bugzilla and I'm no longer familiar with this code.

**Comment by justdave** [comment]
> @justdave Apologies, we no longer use Bugzilla and I'm no longer familiar with this code.

Do you have any objections if I take what you had so far and run with it?

**Comment by CyberShadow** [comment]
None at all, please do!

**Pull request merged**
